// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { Metadata, MetadataData } from "./tables/Metadata.sol";
import { Count } from "./tables/Count.sol";
import { Bounds, BoundsData } from "./tables/Bounds.sol";
