// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { StatusType } from "./../common.sol";

/**
 * @title IInstrumentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInstrumentSystem {
  error OUT_OF_BOUNDS(int32 distance);

  function add(string memory name, bytes3 color, int32 x, int32 y, int32 z) external;

  function move(uint32 index, int32 x, int32 y, int32 z) external;

  function setStatus(uint32 index, StatusType status) external;
}
